#ifndef MYSQL_AES256_CONFLICT_H
#define MYSQL_AES256_CONFLICT_H

#ifdef PACKAGE
	#undef PACKAGE
#endif
#ifdef PACKAGE_BUGREPORT
	#undef PACKAGE_BUGREPORT
#endif
#ifdef PACKAGE_NAME
	#undef PACKAGE_NAME
#endif
#ifdef PACKAGE_STRING
	#undef PACKAGE_STRING
#endif
#ifdef PACKAGE_TARNAME
	#undef PACKAGE_TARNAME
#endif
#ifdef PACKAGE_VERSION
	#undef PACKAGE_VERSION
#endif
#ifdef VERSION
	#undef VERSION
#endif

#endif /* MYSQL_AES256_CONFLICT_H */
